#!/usr/bin/env bash
#Brief: Performs basic tests

set -e # Exit on first failure

echo -e "\nBuilding in debug mode\n"
make FC=ifort OMP=set DEBUG=set rebuild

echo -e "\nExecuting ccd init followed by ccd run a few times\n"
ccd init
ccd run -n -f
ccd run -n -f -a
ccd run -n -f
ccd cpt_to_xy
