#! /usr/bin/env bash
# Brief: This script extracts all TODOs from the given source file(s)
# Synopsis: <this> <file.f90> ...
grep --ignore-case --color --byte-offset --line-number --with-filename --initial-tab todo "${@}"
