#!/usr/bin/env bash
# I conduct tests on the codebase. Kindly make me a git-hook for auto pre-commit run
# Use this command: git config --local core.hooksPath hooks/

set -e # Error exit on first failure

 # Test build with gfortran and OpenMP
echo -e "\nBuilding with gfortran and OpenMP:\n"
make rebuild FC=gfortran OMP=set

# Test build with ifort and OpenMP
echo -e "\nBuilding with ifort and OpenMP:\n"
make rebuild FC=ifort OMP=set

# Linting
echo -e "\n\e[1;31mDont forget to use fortran-linter later on for inplace autofixing code style\e[;0m"

# Further tests

# Status report
echo -e "\n\e[1;32mPassed\e[;0m"
