#!/usr/bin/env bash
# I conduct tests on the codebase. Kindly make me a git-hook for auto pre-commit run
# Use this command: git config --local core.hooksPath hooks/

set -e # Error exit on first failure

 # Test build with gfortran
echo -e "\nBuilding with gfortran:\n"
make rebuild FC=gfortran

# Test build with ifort
echo -e "\nBuilding with ifort:\n"
make rebuild FC=ifort

# Linting
echo -e "\n\e[1;31mDont forget to use fortran-linter later on for inplace autofixing code style\e[;0m"

# Further tests

# Status report
echo -e "\n\e[1;32mPassed\e[;0m"
