#!/usr/bin/env bash
# I conduct tests on the codebase. Kindly make me a git-hook for auto pre-commit run
# Use this command: git config --local core.hooksPath hooks/

set -e # Error exit on first failure
make rebuild FC=gfortran # Test build with gfortran
make rebuild FC=ifort # Test build with ifort

# Linting
echo -e "\n\e[1;31mDont forget to use fortran-linter later on for inplace autofixing code style\e[;0m"

# Further tests

# Status report
echo -e "\n\e[1;32mPassed\e[;0m"
