#! /usr/bin/env bash

whereami(){
  # Returns the absolute path of the directory this script is in
  case "${BASH_SOURCE}" in
    /*)
      echo -n "${BASH_SOURCE%/*}" ;;
    */*)
      echo -n "${PWD}/${BASH_SOURCE%/*}" ;;
    *)
      echo -n "${PWD}";;
  esac
}
this_script_is_at="$(whereami)"

subcmd="${1}"

export PATH="${this_script_is_at}/ccd_:${PATH}"

if [[ -z "${subcmd}" ]]; then
    echo 'Press <Tab> twice after `ccd <space>` to know the available commands'
    exit
fi

shift
"ccd_${subcmd}" "${@}"
