#!/usr/bin/env bash
# This executable is called by ccd driver when invoked with no subcommand

cat <<- EOF

  Collective Cell Dynamics (2D)
  =============================

 Usage: ccd [[-p <parameter>=<value>] <subcommand> [options]]
 ** To see available subcommands: ccd<SPACE><TAB><TAB>
 ** Parameter values may be passed using the -p option

 Repository: https://github.com/PhyBi/Collective-Cell-Dynamics

 ** Checkout the repository for details such as About, Docs, License, Contributors etc.

EOF
