#! /usr/bin/env bash

whereami(){
  # Returns the absolute path of the directory this script is in
  case "${BASH_SOURCE}" in
    /*)
      echo -n "${BASH_SOURCE%/*}" ;;
    */*)
      echo -n "${PWD}/${BASH_SOURCE%/*}" ;;
    *)
      echo -n "${PWD}";;
  esac
}
this_script_is_at="$(whereami)"

invocation="${0}"
package="${invocation##*/}"

export PATH="${this_script_is_at}/${package}_:${PATH}"

subcmd="${1}"
shift

if [[ -z "${subcmd}" ]]; then
    echo 'Press <Tab> twice after `'${package}' <space>` to know the available commands'
    exit
fi

${package}_${subcmd} "${@}"
