#! /usr/bin/env bash

whereami(){
  # Returns the absolute path of the directory this script is in
  case "${BASH_SOURCE}" in
    /*)
      echo -n "${BASH_SOURCE%/*}" ;;
    */*)
      echo -n "${PWD}/${BASH_SOURCE%/*}" ;;
    *)
      echo -n "${PWD}";;
  esac
}
this_script_is_at="$(whereami)"

invocation="${0}"
package="${invocation##*/}"

export PATH="${this_script_is_at}/${package}_:${PATH}"
[[ -n "${PARAMS_FILE}" ]] || PARAMS_FILE="params.in"
export PARAMS_FILE
sed '1i &params ! Namelist header' <(cat "${PARAMS_FILE}" 2>/dev/null; echo) > .params.in
echo '/ ! Namelist footer' >> .params.in

subcmd="${1}"
shift

if [[ -z "${subcmd}" ]]; then
  echo 'Press <Tab> twice after `'${package}' <space>` to know the available commands'
else
  ${package}_${subcmd} "${@}"
fi

rm -f .params.in
